// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'document_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `yrs_any_to_json`, `yrs_value_to_json`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DocumentService>>
abstract class DocumentService implements RustOpaqueInterface {
  Future<Uint8List> applyAction({required List<BlockActionDoc> actions});

  Future<void> applyUpdates({required List<Uint8List> updates});

  /// 모든 메타데이터를 JSON 문자열로 반환
  ///
  /// 반환: JSON 형식의 메타데이터 (예: {"title": "노트", "color": 123, "status": "active"})
  Future<String> getAllMeta();

  Future<DocumentState> getDocumentState();

  Future<Uint8List> initEmptyDoc();

  Future<Uint8List> mergeUpdates({required List<Uint8List> updates});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DocumentService> newInstance() =>
      RustLib.instance.api.crateDocDocumentServiceDocumentServiceNew();

  /// 메타데이터 배열에 문자열 항목 추가 (중복 체크)
  ///
  /// [key] 메타데이터 키
  /// [value] 추가할 문자열 값
  Future<Uint8List> pushMetaArrayItem({
    required String key,
    required String value,
  });

  /// 메타데이터 배열에서 문자열 항목 제거
  ///
  /// [key] 메타데이터 키
  /// [value] 제거할 문자열 값
  Future<Uint8List> removeMetaArrayItem({
    required String key,
    required String value,
  });

  /// 메타데이터 키 제거
  ///
  /// [key] 제거할 메타데이터 키
  Future<Uint8List> removeMetaKey({required String key});

  /// 메타데이터에 불리언 값 설정
  ///
  /// [key] 메타데이터 키
  /// [value] 설정할 불리언 값
  Future<Uint8List> setMetaBool({required String key, required bool value});

  /// 여러 메타데이터 필드를 한 번에 설정 (JSON 입력)
  ///
  /// [json_str] 설정할 메타데이터 JSON (예: {"title": "노트", "status": "active"})
  ///
  /// 지원 타입: string, number (int/double), boolean, string array
  Future<Uint8List> setMetaFromJson({required String jsonStr});

  /// 메타데이터에 정수 값 설정
  ///
  /// [key] 메타데이터 키
  /// [value] 설정할 정수 값
  Future<Uint8List> setMetaInt({
    required String key,
    required PlatformInt64 value,
  });

  /// 메타데이터에 문자열 값 설정
  ///
  /// [key] 메타데이터 키
  /// [value] 설정할 문자열 값
  Future<Uint8List> setMetaString({required String key, required String value});

  /// 메타데이터에 문자열 배열 설정 (기존 배열 전체 교체)
  ///
  /// [key] 메타데이터 키
  /// [values] 설정할 문자열 배열
  Future<Uint8List> setMetaStringArray({
    required String key,
    required List<String> values,
  });

  /// Setting a root node id in the root map
  Future<Uint8List> setRootNodeId({required String id});
}
